SET SERVEROUTPUT ON; 

CREATE OR REPLACE PACKAGE INSERSION_TABLAS AS

   
    PROCEDURE INSERTAR_MONTO_INGRESO(
        p_ingreso   IN MONTO_INGRESO.INGRESO%TYPE,
        p_nro_cliente IN MONTO_INGRESO.NRO_CLIENTE%TYPE
    );

    
    PROCEDURE INSERTAR_ESTADO_CREDITO_CLIENTE(
        p_nro_cliente IN ESTADO_CREDITO_CLIENTE.NRO_CLIENTE%TYPE,
        p_hipotecario IN ESTADO_CREDITO_CLIENTE.ESTADO_HIPOTECARIO%TYPE,
        p_consumo IN ESTADO_CREDITO_CLIENTE.ESTADO_CONSUMO%TYPE,
        p_automotriz IN ESTADO_CREDITO_CLIENTE.ESTADO_AUTOMOTRIZ%TYPE,
        p_emergencia IN ESTADO_CREDITO_CLIENTE.ESTADO_EMERGENCIA%TYPE,
        p_arancel IN ESTADO_CREDITO_CLIENTE.ESTADO_ARANCEL%TYPE
    );
    
END INSERSION_TABLAS;
/

CREATE OR REPLACE PACKAGE BODY INSERSION_TABLAS AS
    PROCEDURE INSERTAR_MONTO_INGRESO(
        p_ingreso   IN MONTO_INGRESO.INGRESO%TYPE,
        p_nro_cliente IN MONTO_INGRESO.NRO_CLIENTE%TYPE)
    IS  
    BEGIN
        
        INSERT INTO MONTO_INGRESO (
            COD_MONTO_INGRESO,
            INGRESO,
            NRO_CLIENTE)
        VALUES (
            NULL,
            p_ingreso,
            p_nro_cliente);

        COMMIT;
        
    END INSERTAR_MONTO_INGRESO;

    PROCEDURE INSERTAR_ESTADO_CREDITO_CLIENTE(
    p_nro_cliente IN ESTADO_CREDITO_CLIENTE.NRO_CLIENTE%TYPE,
    p_hipotecario IN ESTADO_CREDITO_CLIENTE.ESTADO_HIPOTECARIO%TYPE,
    p_consumo IN ESTADO_CREDITO_CLIENTE.ESTADO_CONSUMO%TYPE,
    p_automotriz IN ESTADO_CREDITO_CLIENTE.ESTADO_AUTOMOTRIZ%TYPE,
    p_emergencia IN ESTADO_CREDITO_CLIENTE.ESTADO_EMERGENCIA%TYPE,
    p_arancel IN ESTADO_CREDITO_CLIENTE.ESTADO_ARANCEL%TYPE)
    
    IS 
    
    BEGIN
    
    INSERT INTO ESTADO_CREDITO_CLIENTE(
    COD_ESTADO_CREDITO_CLIENTE,
        ESTADO_HIPOTECARIO,
        ESTADO_CONSUMO,
        ESTADO_AUTOMOTRIZ,
        ESTADO_EMERGENCIA,
        ESTADO_ARANCEL,
        NRO_CLIENTE)
    
    VALUES (
        NULL,
        p_hipotecario,
        p_consumo,
        p_automotriz,
        p_emergencia,
        p_arancel,
        p_nro_cliente
    );

    COMMIT;
    
    END INSERTAR_ESTADO_CREDITO_CLIENTE;
        

END INSERSION_TABLAS;



CREATE OR REPLACE PACKAGE VALIDACION_CREDITOS AS

   
    FUNCTION CREDITO_HIPOTECARIO(
        P_INGRESO MONTO_INGRESO.ingreso%TYPE, 
        P_COD_TIPO_CLIENTE TIPO_CLIENTE.COD_TIPO_CLIENTE%TYPE
    )
    RETURN BOOLEAN;

    
    FUNCTION CREDITO_CONSUMO(
        P_INGRESO MONTO_INGRESO.ingreso%TYPE
    )
    RETURN BOOLEAN;
    
    
    FUNCTION CREDITO_AUTOMOTRIZ(
        P_INGRESO MONTO_INGRESO.ingreso%TYPE, 
        P_COD_TIPO_CLIENTE TIPO_CLIENTE.COD_TIPO_CLIENTE%TYPE
    )
    RETURN BOOLEAN;
    
  
    FUNCTION CREDITO_EMERGENCIA(
        P_INGRESO MONTO_INGRESO.ingreso%TYPE, 
        P_COD_TIPO_CLIENTE TIPO_CLIENTE.COD_TIPO_CLIENTE%TYPE
    )
    RETURN BOOLEAN;
    
    
    FUNCTION CREDITO_PAGO_ARANCEL(
        P_INGRESO MONTO_INGRESO.ingreso%TYPE, 
        P_COD_TIPO_CLIENTE TIPO_CLIENTE.COD_TIPO_CLIENTE%TYPE
    )
    RETURN BOOLEAN;
    
END VALIDACION_CREDITOS;
/



CREATE OR REPLACE PACKAGE BODY VALIDACION_CREDITOS AS

    FUNCTION CREDITO_HIPOTECARIO(P_INGRESO MONTO_INGRESO.ingreso%type, P_COD_TIPO_CLIENTE TIPO_CLIENTE.COD_TIPO_CLIENTE%TYPE)        
    
        RETURN BOOLEAN
    IS
        
        
    BEGIN
        RETURN (P_INGRESO >= 1500000) AND (P_COD_TIPO_CLIENTE IN (1,2));
    END CREDITO_HIPOTECARIO;
    
    FUNCTION CREDITO_CONSUMO(P_INGRESO MONTO_INGRESO.ingreso%type)        
    
        RETURN BOOLEAN
    IS
        
        
    BEGIN
        RETURN (P_INGRESO >= 900000);
    END CREDITO_CONSUMO;
    
    
    FUNCTION CREDITO_AUTOMOTRIZ(P_INGRESO MONTO_INGRESO.ingreso%type, P_COD_TIPO_CLIENTE TIPO_CLIENTE.COD_TIPO_CLIENTE%TYPE)        
    
        RETURN BOOLEAN
    IS
        
        
    BEGIN
        RETURN (P_INGRESO >= 900000) AND (P_COD_TIPO_CLIENTE IN (1,2));
    END CREDITO_AUTOMOTRIZ; 
         
         
     FUNCTION CREDITO_EMERGENCIA(P_INGRESO MONTO_INGRESO.ingreso%type, P_COD_TIPO_CLIENTE TIPO_CLIENTE.COD_TIPO_CLIENTE%TYPE)        
    
        RETURN BOOLEAN
    IS
        
        
    BEGIN
        RETURN ((P_INGRESO >= 900000) AND (P_COD_TIPO_CLIENTE IN (1, 2))) OR ((P_INGRESO >= 150000) AND (P_COD_TIPO_CLIENTE IN (3)));
    
    END CREDITO_EMERGENCIA; 
    
    FUNCTION CREDITO_PAGO_ARANCEL(P_INGRESO MONTO_INGRESO.ingreso%type, P_COD_TIPO_CLIENTE TIPO_CLIENTE.COD_TIPO_CLIENTE%TYPE)        
    
        RETURN BOOLEAN
    IS
        
        
    BEGIN
        RETURN (P_INGRESO >= 900000) AND (P_COD_TIPO_CLIENTE IN (1,2));
    END CREDITO_PAGO_ARANCEL;
         
           
    
END VALIDACION_CREDITOS;
/

DECLARE

    V_COD_MONTO_INGRESO MONTO_INGRESO.cod_monto_ingreso%type;
    V_INGRESO MONTO_INGRESO.ingreso%type;
    V_N_TIPO_CLIENTE TIPO_CLIENTE.cod_tipo_cliente%type;
    
    V_RESULTADO_HIPOTECARIO ESTADO_CREDITO_CLIENTE.ESTADO_HIPOTECARIO%TYPE;
    V_RESULTADO_CONSUMO ESTADO_CREDITO_CLIENTE.ESTADO_CONSUMO%TYPE;
    V_RESULTADO_AUTOMOTRIZ ESTADO_CREDITO_CLIENTE.ESTADO_AUTOMOTRIZ%TYPE;
    V_RESULTADO_EMERGENCIA ESTADO_CREDITO_CLIENTE.ESTADO_EMERGENCIA%TYPE;
    V_RESULTADO_ARANCEL ESTADO_CREDITO_CLIENTE.ESTADO_ARANCEL%TYPE;
    
    
    V_CONTADOR NUMBER(20);

      CURSOR CUR_INGRESO IS
        SELECT 
            MI.COD_MONTO_INGRESO AS "ID_MONTO_INGRESO"
            , MI.INGRESO AS "INGRESO"
            , TC.COD_TIPO_CLIENTE AS "ID_TIPO_CLIENTE"
            , c.nro_cliente AS "ID_CLIENTE"
       
        FROM MONTO_INGRESO MI
        JOIN CLIENTE C ON C.NRO_CLIENTE = mi.nro_cliente
        JOIN TIPO_CLIENTE TC ON TC.COD_TIPO_CLIENTE = C.COD_TIPO_CLIENTE;


    

    BEGIN
        FOR I IN CUR_INGRESO
            LOOP
            
            --VERIFICO CREDITOS APROBADOS 1 O DESAPROBADOS 0
                IF(validacion_creditos.credito_hipotecario(I.INGRESO,I.ID_TIPO_CLIENTE)) THEN 
                    V_RESULTADO_HIPOTECARIO:= 1;
                    ELSE 
                        V_RESULTADO_HIPOTECARIO:= 0;
                    END IF;           

                IF(validacion_creditos.credito_consumo(I.INGRESO)) THEN 
                        V_RESULTADO_CONSUMO:= 1;
                    ELSE 
                        V_RESULTADO_CONSUMO:= 0;
                    END IF;

                IF(validacion_creditos.credito_automotriz(I.INGRESO,I.ID_TIPO_CLIENTE)) THEN 
                        V_RESULTADO_AUTOMOTRIZ:= 1;
                    ELSE 
                        V_RESULTADO_AUTOMOTRIZ:= 0;
                    END IF;

                IF(validacion_creditos.credito_emergencia(I.INGRESO,I.ID_TIPO_CLIENTE)) THEN 
                        V_RESULTADO_EMERGENCIA:= 1;
                    ELSE 
                        V_RESULTADO_EMERGENCIA:= 0;
                    END IF;
                    
                IF(validacion_creditos.credito_pago_arancel(I.INGRESO,I.ID_TIPO_CLIENTE)) THEN 
                        V_RESULTADO_ARANCEL:= 1;
                    ELSE 
                        V_RESULTADO_ARANCEL:= 0;
                    END IF;
                    
                    
                    SELECT COUNT(*)
                        INTO V_CONTADOR
                        FROM ESTADO_CREDITO_CLIENTE ECC
                        WHERE ECC.NRO_CLIENTE = I.ID_CLIENTE; -- CUENTA SI ES QUE EXISTE YA EL ID
                    
                    IF V_CONTADOR = 0 THEN -- SI ES 0 ES PORQUE NO ESTA EL ID, POR LO TANTO PROCEDE A INSERTAR
                        INSERSION_TABLAS.INSERTAR_ESTADO_CREDITO_CLIENTE(
                            p_nro_cliente => I.ID_CLIENTE,
                            p_hipotecario => V_RESULTADO_HIPOTECARIO,
                            p_consumo => V_RESULTADO_CONSUMO,
                            p_automotriz => V_RESULTADO_AUTOMOTRIZ,
                            p_emergencia => V_RESULTADO_EMERGENCIA,
                            p_arancel => V_RESULTADO_ARANCEL
                        );
                        
                    END IF;
                    
           
            
            END LOOP;
            COMMIT;
            DBMS_OUTPUT.PUT_LINE('Proceso completado exitosamente');
    
END;
/





CREATE TABLE MONTO_INGRESO(
    COD_MONTO_INGRESO NUMBER(5,0)PRIMARY KEY,
    INGRESO NUMBER(20),
    NRO_CLIENTE NUMBER(5,0),
    FOREIGN KEY(NRO_CLIENTE) REFERENCES CLIENTE(NRO_CLIENTE),
    UNIQUE(NRO_CLIENTE)
);


CREATE TABLE ESTADO_CREDITO_CLIENTE (
    COD_ESTADO_CREDITO_CLIENTE NUMBER(5,0) PRIMARY KEY,
    ESTADO_HIPOTECARIO NUMBER(1,0), --1 = TRUE 0 = FALSE
    ESTADO_CONSUMO NUMBER(1,0),
    ESTADO_AUTOMOTRIZ NUMBER(1,0),
    ESTADO_EMERGENCIA NUMBER(1,0),
    ESTADO_ARANCEL NUMBER(1,0),
    NRO_CLIENTE NUMBER(5,0),
    FOREIGN KEY(NRO_CLIENTE) REFERENCES CLIENTE(NRO_CLIENTE),
    UNIQUE(NRO_CLIENTE)
);

CREATE SEQUENCE SEQ_ID_MONTO_INGRESO
START WITH 1      
INCREMENT BY 1    
NOCACHE;

CREATE OR REPLACE TRIGGER TRG_SEQ_ID_MONTO_INGRESO
BEFORE INSERT ON MONTO_INGRESO

    FOR EACH ROW
        BEGIN 
            IF :NEW.COD_MONTO_INGRESO IS NULL THEN
                SELECT SEQ_ID_MONTO_INGRESO.NEXTVAL 
                INTO :NEW.COD_MONTO_INGRESO
                FROM DUAL; --SOLO PARA SINTAXIS
            END IF;
END;


CREATE  SEQUENCE SEQ_ID_ESTADO_CREDITO_CLIENTE
START WITH 1      
INCREMENT BY 1    
NOCACHE;



CREATE OR REPLACE TRIGGER TRG_SEQ_ID_ESTADO_CREDITO_CLIENTE
BEFORE INSERT ON ESTADO_CREDITO_CLIENTE

    FOR EACH ROW
        BEGIN 
            IF :NEW.COD_ESTADO_CREDITO_CLIENTE IS NULL THEN
                SELECT SEQ_ID_ESTADO_CREDITO_CLIENTE.NEXTVAL 
                INTO :NEW.COD_ESTADO_CREDITO_CLIENTE
                FROM DUAL; --SOLO PARA SINTAXIS
            END IF;
END;



TRUNCATE TABLE ESTADO_CREDITO_CLIENTE;


-- DEBE CONTAR CON VALORES LA TABLA MONTO_INGRESO PARA HACER LAS VALIDACIONES
-- EL SISTEMA YA PROTEGE DE SOBREESCRITURA













